version: '3'

services:

  nginx:
    image: nginx:latest
    ports:
      - "3030:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx.d/default.conf
    depends_on:
      - cliente
  backend:
    image: photo-social-backend:1
    build:
      context: ./Server/app
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - cliente
  cliente:
    build:
      context: ./Public
    container_name: cliente
    ports:
      - "12345:12345"