version: '3'

services:

  cloner:
    image: alpine/git
    volumes:
      - backend_data:/data
    command: clone https://github.com/chris979712/photo-social-backend.git /data

  backend:
    build:
      context: /data  
    volumes:
      - backend_data:/data
    depends_on:
      - cloner
    ports:
      - "5000:5000"
  nginx:
    image: nginx:latest
    ports:
      - "3030:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx.d/default.conf
    depends_on:
      - cliente
  cliente:
    build:
      context: ./Public
    container_name: cliente_backend
    ports:
      - "12345:12345"