version: '3'

services:

  nginx:
    image: nginx:latest
    ports:
      - "3030:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx.d/default.conf
    depends_on:
      - cliente
  backend:
    build:
      context: ./photo-social-backend
    ports:
      - "5000:5000"
    depends_on:
      - cliente
  cliente:
    build:
      context: .
    container_name: cliente_backend
    ports:
      - "12345:12345"